DROP TABLE IF EXISTS TB_BRAND_CATEGORY;
CREATE TABLE TB_BRAND_CATEGORY (
    BRAND VARCHAR(1),
    CATEGORY VARCHAR(20),
    PRICE BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_BRAND_CATEGORY PRIMARY KEY (BRAND, CATEGORY)  -- 유니크 제약 조건 추가
);