DROP TABLE IF EXISTS TB_PRODUCT_BRAND_CATEGORY;
CREATE TABLE TB_PRODUCT_BRAND_CATEGORY (
    BRAND VARCHAR(8),
    CATEGORY VARCHAR(128),
    PRICE BIGINT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_BRAND_CATEGORY PRIMARY KEY (BRAND, CATEGORY)
);